version: "3.9"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db

  scheduler:
    build: ./fantasy2021/fantasyscheduler/

  api:
    build: ./fantasy2021/fantasyapi/
    ports:
      - "8080:8080"

  web:
    build: ./nginx-web-server/
    ports:
      - "80:80"
